### PR TITLE
Added a 5 seconds delay before disabling actuators on penalty

### LINKED ISSUE #143: `player` should not disable the actuators when a robot is penalized
**Describe the Bug**
When the robot is penalized, it is set to the side of the field and its actuators are disabled. But when the robot is not in a stable position when it is penalized, it cannot reset itself to a stable position and will fall again when the auto referee stops holding it up. The fall results in another penalty and so on.

**Expected behavior**
The robot should be able to move its actuators when it gets penalized so that it can recover from unstable positions.

### PR DESCRIPTION
**Pull request by omichel**
Fixed #143.

### CODE REVIEW

**Comment by timonegk** [comment]
This is still not working for us. To reproduce, we just set one motor to a specific position all the time and when we get penalized, the motor position is reset and does not change at all.

**Comment by omichel** [comment]
Yes, this is because for one virtual second, the robot is forced to its original position in order to stabilize it.
Normally, after that, you should be able to move the motors of the robot until second 5.
If needed I can extend the 5 seconds timeout, because it is actually 4 seconds (since during the first second the robot position is reset constantly).

**Comment by timonegk** [comment]
I think with #125, this solution is actually no longer needed because the underlying problem, that we need to be in a stable position when we are penalized, no longer exists. We were still on an older commit when we observed the problem. Since with the change in #125, the motor positions at reentry are always the same, we can work with that. Sorry about the fuss.

**Comment by omichel** [comment]
OK, I will try to remove the stabilization code and see if the tests are still passing.

**Comment by omichel** [comment]
Removing the stabilization code breaks the following tests:
```
forceful_contact/competing_for_ball
forceful_contact/far_from_ball
```

**Comment by medrimonia** [comment]
I think the most likely issue is that the test still apply velocity after the robot has been reset, I'll need to solve this after the mock-comp so that we avoid false positives on those tests or confirm if the failure is due to an Autoref issue.

**Comment by omichel** [comment]
But reducing the stabilization duration from one second to 0.1 second make all the tests pass again.
That would leave 4.9 seconds after those 0.1 second stabilization time elapsed for the robot to move.

**Comment by omichel** [comment]
I would rather suspect that after violent robot collisions, the physics engine is slightly messed up at the joint level (e.g., joints are moved away from their normal positions) and needs a couple of iterations to stabilize.

**Comment by omichel** [comment]
I will try to further reduce the stabilization time to see what's the limit for the tests to pass.

**Comment by timonegk** [comment]
What I meant is that the fix is actually no longer necessary and the issue can be closed, at least for our team, because of #125.

**Comment by omichel** [comment]
> What I meant is that the fix is actually no longer necessary and the issue can be closed, at least for our team, because of #125.

Understood.

Nevertheless this PR improves the performance of the referee in the sense that it performs a single extra call to physicsReset to stabilize penalized robots. So, I would suggest to remove the code related to the 5 seconds before disabling the actuators, but keep the code related to optimized stabilization.

**Comment by omichel** [comment]
I tested this PR with the test suite and 100% of the tests are passing.
This PR speeds up the referee when robots are penalized and being stabilized.
I believe it is safe to merge it.

**Pull request merged**
