### PR TITLE
Various fixes for forceful contact rules

### PR DESCRIPTION
**Pull request by omichel**
- [x] 1. At L484 of the rule book (right after the ball holding), it is stated that "if an offense did not happen within a radius of approx. 1m around the current ball position or if the ball is not in play, the direct free kick is replaced by a removal penalty". This applies to forceful contact as well.

- [x] 2. Since the ball is out of play during a freekick, it is impossible to start a freekick during another freekick. In this case, removal penalty should be applied. In the current implementation, freekick is called at every tick until the collision stops which has as consequence a major slowdown of the simulation since the Referee is waiting for the GameController to answer after every directkick request. It is very difficult to fix the test_scenarios with this behavior.

- [x] 3. Problem 2 makes it pretty clear that we will need an 'immunity duration' once a forceful contact has been detected, otherwise the robot that triggered the freekick is likely to receive a removal penalty on the following tick. I think that 2 seconds would be a good value to start this implementation.

- [x] 4. It is quite critical to refactor the 'check_forceful_contact' function. It is a symmetrical problem, therefore duplicating the code is much more likely to lead to bugs and much harder to maintain than simply calling: analyze_forceful_contact(team_1,number_1, team_2, number_2) and then analyze_forceful_contact(team_2,number_2,team_1,number_1).

### CODE REVIEW

**Comment by medrimonia** [comment]
I was able to check and I have two comments:

1. The call from the referee should not be `INCAPABLE` but `PHYSICAL_CONTACT`, I fixed it and realized that there was a bug in the GameController for those calls: https://github.com/RoboCup-Humanoid-TC/GameController/pull/148

2. The immunity period at start of Freekick doesn't seem to be working properly yet, see logs of referee below:

```
[0025.659|0195.104] Info: Sending 24405:DIRECT_FREEKICK:9 to GameController.
[0025.659|0195.104] Info: Waiting for GameController to answer to 24405:DIRECT_FREEKICK:9.
[0025.859|0195.104] Info: Waiting for GameController to answer to 24405:DIRECT_FREEKICK:9.
[0026.072|0195.112] Info: Awarding a direct free kick.
[0026.072|0195.112] Info: 195112: contact between red player 1 and blue player 1.
[0026.073|0195.112] Info: Blue player 1 committed a forceful contact foul on red player 1 (opponent moving towards the ball) outside penalty area.
[0026.073|0195.112] Info: Sending 24409:PENALTY:7:1:PHYSICAL_CONTACT to GameController.
```

I have also noticed that even when penalty is properly called and accepted by the referee with the fix, the test still consider the robot as 'unpenalized', but this is probably an issue with the GameController that we'll need to investigate with @MaikePaetzel .

**Comment by omichel** [comment]
The `forceful_contact/charging` test is failing because the game controller doesn't send the correct status about the PHYSICAL_CONTACT penalty, which it considers illegal. I guess this is due to a bug in the GameController. So, I will stop working on this test until the GameController is fixed.

**Comment by omichel** [comment]
The `forceful_contact/far_from_ball` test is now failing for the same reason as `forceful_contact/charging`. I believe that once the GameController is fixed with respect to `PHYSICAL_CONTACT` penalty, both should pass at least one step further. Meanwhile, `forceful_contact/same_team` is fully passing. So, I will wait for GameController fix to continue to work on these two failing tests.

**Comment by omichel** [comment]
Here are the results of the tests on this branch:
```
PASS 12/12 ./ball_holding/multi_robot_kid
PASS  4/ 4 ./ball_out/corner
PASS  4/ 4 ./ball_out/goal_kick
PASS  5/ 5 ./ball_out/throw_in
FAIL 10/12 ./forceful_contact/charging
FAIL 10/12 ./forceful_contact/far_from_ball
PASS  6/ 6 ./forceful_contact/same_team
PASS 13/13 ./game_interruptions/corner/procedure
PASS  7/ 7 ./game_interruptions/corner/scoring/goal
PASS  8/ 8 ./game_interruptions/corner/scoring/own_goal
PASS 17/17 ./game_interruptions/goal_kick/procedure
PASS  7/ 7 ./game_interruptions/goal_kick/scoring/goal
PASS  8/ 8 ./game_interruptions/goal_kick/scoring/own_goal
PASS 12/12 ./game_interruptions/throw_in/procedure
PASS  7/ 7 ./game_interruptions/throw_in/scoring/bouncing_goal
PASS  7/ 7 ./game_interruptions/throw_in/scoring/goal
PASS  7/ 7 ./game_interruptions/throw_in/scoring/own_goal
PASS 10/10 ./game_phases/dropped_ball
PASS  2/ 2 ./game_phases/initial
PASS 13/13 ./game_phases/kick_off/scenario_1
PASS 11/11 ./game_phases/kick_off/scenario_2
PASS  3/ 3 ./game_phases/kick_off/scenario_3
PASS  5/ 5 ./game_phases/kick_off/scenario_4
PASS  3/ 3 ./game_phases/kick_off/scenario_5
PASS 28/28 ./game_phases/penalty_shootouts
PASS 14/14 ./game_phases/repositioning
FAIL  9/16 ./game_phases/second_half
PASS 24/24 ./misc_fouls/inactive_goalie
PASS  4/ 4 ./misc_fouls/leaving_field
PASS 28/28 ./positioning/initial
PASS 15/15 ./positioning/ready
PASS 14/14 ./results/draw
PASS  9/ 9 ./results/win
PASS  6/ 6 ./scoring/goal
PASS  5/ 5 ./scoring/over_goal
PASS  4/ 4 ./scoring/own_goal
==========================
# GLOBAL RESULTS: 351/362 #
==========================
```

**Comment by medrimonia** [comment]
The implementation change solved the first INITIAL duration problem,  but it broke some tests. I fixed the following:

- `positioning/initial`
- `positioning/ready`
- `game_phases/initial`

However, it still increased the failures of `game_phases/second_half` because `time.time() - game.start_real_time` is true at the first tick of the second half. `game.start_real_time` should be set properly each time we enter a state with fixed real time duration.

For the `forceful_contact/charging`, apparently the problem was not in the GameController, but the scenario checked for a penalty too soon, this is fixed now. However two tests are still not passing in this scenario:

- `Test C. Player moving away too fast -> pushing` I checked and the AutoRef does not issue a penalty in this case
- `Test D. Since freekick -> No penalty`, I checked and got the following:
```
[0022.859|0186.256] Info: Waiting for GameController to answer to 23299:DIRECT_FREEKICK:9.
[0023.059|0186.256] Info: Waiting for GameController to answer to 23299:DIRECT_FREEKICK:9.
[0023.271|0186.264] Info: Awarding a direct free kick.
[0023.271|0186.264] Info: 186264: contact between red player 1 and blue player 1.
[0023.271|0186.264] Info: Blue player 1 committed a forceful contact foul on red player 1 (opponent moving towards the ball) outside penalty area.
[0023.272|0186.264] Info: Sending 23303:PENALTY:7:1:PHYSICAL_CONTACT to GameController.
```
Apparently, the immunity period is not working as intended, or at least in some case it does not have the expected effect.

For the `forceful_contact/far_from_ball`, the problem that I have seen appearing is not related to the GameController. What happens is that the robot `RED_1` has a tendency to fall after being replaced on the `penaltyReentryPose` which leads it to an 'incapable robot' penalty, making the next test fall.
While this could be solved in the test, I think that it's a problem of the AutoRef because when respawn at `penaltyReentryPose`, the physics should be reset and the robot should not have momentum anymore.

**Comment by medrimonia** [comment]
I added another test scenario which mostly passed without requiring changes to the AutoRef. There's only 1 test failing because of the inertia that robots have when they receive a removal penalty, but this was already identified.

**Comment by omichel** [comment]
Thank you for fixing these scenarios.
All the tests are now passing, except for the forceful_contact ones.
Would you like me to remove the forceful_contact tests from the `launch_all_test.sh` script or can we merge this PR to the experimental branch as is?

**Comment by medrimonia** [comment]
We can merge this, I'll just run a full test on the resulting experimental branch and then I'll merge it on the release one.

**Comment by omichel** [comment]
The problem with the forceful_contact/charging test is that the GameController is returning an error when the referee sends the PHYSICAL_CONTACT penalty. So, I am still suspecting a problem in the GameController:
```
Received illegal answer from GameController for message 14421:PENALTY:9:1:PHYSICAL_CONTACT.
```
@medrimonia: are you getting the same error?

**Comment by omichel** [comment]
When sending an `INCAPABLE` penalty instead of the `PHYSICAL_CONTACT` penalty, I am not getting the illegal error from the GameController, but the test fails because it expects a `PHYSICAL_CONTACT` penalty instead of an `INCAPABLE` penalty.

**Comment by omichel** [comment]
I found out that running the GameController from [this branch](https://github.com/RoboCup-Humanoid-TC/GameController/tree/advanced-autoref-updates) fixes the illegal error. I will continue from there.

**Comment by medrimonia** [comment]
Yes, we mentioned it last week, but it has not been merged yet. It is better to use the `advanced-autoref-updates` for development.

**Pull request merged**
