### PR TITLE
Supporting running tests on Windows

### PR DESCRIPTION
**Pull request by omichel**
This PR introduces a better way to reuse the `gamestate.py` module from the test_supervisor.
It also fixes the test launcher to support Windows.

### CODE REVIEW

**Comment by medrimonia** [comment]
While my `WEBOTS_HOME` environment variable is properly set, this still leads me to:
```
Traceback (most recent call last):
  File "test_supervisor.py", line 3, in <module>
    from gamestate import GameState
ModuleNotFoundError: No module named 'gamestate'
WARNING: 'test_supervisor' controller exited with status: 1.
```

Is there any additional step to take?

**Comment by omichel** [comment]
That's odd. I will test on Linux tomorrow morning to see if I can reproduce the problem.
On Windows, it works fine.

**Comment by omichel** [comment]
I have indeed the same problem as you on Linux, but I could work around it by setting:
```bash
export PYTHONPATH=/path/to/webots/projects/samples/contests/robocup/controllers/referee
```
I will further investigate why it doesn't work as expected from the `runtime.ini` file.

**Comment by omichel** [comment]
I just pushed a quick fix for Linux, but will further investigate for a better fix.

**Comment by medrimonia** [comment]
The fix works for me, thanks!

**Comment by omichel** [comment]
That is actually a [bug](https://github.com/cyberbotics/webots/issues/3011) affecting only the Linux and macOS versions of Webots. I will merge my patch as is until the bug is fixed.

**Pull request merged**
