### PR TITLE
Ball out of play test

### PR DESCRIPTION
**Pull request by SoheilKhatibi**
This PR is aimed to test the procedure of re-spawning the ball into the field of play after leaving the field in different situations. It relates to issue #14 .

### CODE REVIEW

**Comment by SoheilKhatibi** [comment]
This is the actual log I got while running this scenario:
```
[0000.001|0000.000] Error: Host is not correctly defined in game.json file, it should be 127.0.1.1 instead of 192.168.1.133.
[0000.003|0000.000] Info: Real time factor is set to 0. Simulation will run as fast as possible, real time waiting times will be minimised.
[0001.504|0000.000] Info: Spawned RED_PLAYER_1 RobocupRobot on port 10001 at halfTimeStartingPose: translation -3.5 -3.06 0.24, rotation 0 0 1 1.57
[0002.480|0000.000] Info: Spawned BLUE_PLAYER_1 RobocupRobot on port 10021 at halfTimeStartingPose: translation 3.5 -3.06 0.24, rotation 0 0 1 1.571592653589793
[0002.500|0000.000] Info: Connected to GameControllerSimulator at localhost:8750
[0002.501|0000.000] Info: Red team is Funny Dingos
[0002.501|0000.000] Info: Blue team is Agile Lynxes
[0002.501|0000.000] Info: Left side is red
[0002.501|0000.000] Info: Kickoff is red
[0002.501|0000.000] Info: Sending SIDE_LEFT:1 to GameController
[0002.501|0000.000] Info: Sending KICKOFF:1 to GameController
[0002.552|0000.008] Info: New state received from GameController: STATE_INITIAL
[0005.585|0009.600] Info: Sending STATE:READY to GameController
[0006.051|0011.552] Info: New state received from GameController: STATE_READY
[0018.072|0057.744] Info: New state received from GameController: STATE_SET
[0018.072|0057.744] Info: Sending PENALTY:1:1:INCAPABLE to GameController
[0018.076|0057.744] Info: INCAPABLE penalty for red player 1: did not move to kickoff position. Sent to translation -3 3.11 0.24, rotation 0.0 0.0 1.0 4.711592653589793
[0018.076|0057.744] Info: Sending PENALTY:2:1:INCAPABLE to GameController
[0018.079|0057.744] Info: INCAPABLE penalty for blue player 1: did not move to kickoff position. Sent to translation 3 3.11 0.24, rotation 0.0 0.0 1.0 4.713185307179587
[0020.007|0062.736] Info: Sending STATE:PLAY to GameController
[0020.577|0063.856] Info: New state received from GameController: STATE_PLAYING
[0063.510|0096.792] Error: GameController sent "600 seconds remaining"!
[0063.968|0097.256] Info: Ball touched by red player 1.
[0064.048|0097.304] Info: Ball touched again by same player.
[0064.063|0097.312] Info: Ball touched again by same player.
[0064.071|0097.320] Info: Ball touched again by same player.
[0064.093|0097.328] Info: Ball touched again by same player.
[0132.166|0104.504] Info: Ball left the field at 0.9996886261897017 3.0834884165631036 0.07917275126639203 after being touched by red player 1.
[0134.298|0106.496] Info: Ball respawned at 0.9996886261897017 2.975 0.07917275126639203
```

**Comment by medrimonia** [comment]
For this scenario, I think it is a little bit tricky to test all the different issues with one single scenario because putting the ball out of play launches a complex procedure which implies delays. Moreover, it would be useful to plan the scenario for #14 to be easily extended with #15 in the future.

Moreover, it actually contains many 'unclear' elements that needs rephrasing, an example with: 
> 5. The robot `Red 1` is manually moved into the field, the ball is manually touched by the `Red 1`, and then it entirely crosses the touchline, from `1 3.08 0.08`.
This can be replaced (with X defined) by:
- `Red 1` is moved to `X X X`
- Simulation is paused, a force of X Newton is applied to the ball along X-axis, simulation is resumed
- The ball bounces on `Red 1`
- Simulation is paused, ball is moved to `1 3.08 0.08`
- A force of `X` Newton is applied on the ball along Y-Axis
- Ball leaves the field
- Ball is automatically placed back to `1 3 0.08`

It is better to separate the Ball out of play scenarios in multiple ones and not to place #13 in a scenario testing simple features because it requires to run a whole game and therefore takes some time.

**Comment by SoheilKhatibi** [comment]
I updated the PR applying what you mentioned.

**Comment by medrimonia** [comment]
Ball Being out of Play - touchline, basic case

**Pull request merged**
