### PR TITLE
Automated testing experiment

### PR DESCRIPTION
**Pull request by medrimonia**
This pull request introduces a system to automate the testing of the autoreferee based on `JSON` files. It has been applied successfully to one case, exhibiting a few issues. The entry point is the documentation provided in the `README.md` in the `test_supervisor` folder.

Through the development, I was basically forced to separate the test scenario in two to separate aspects involving 'real time' test and 'simulation time' test. I think that this highlight that ideally those tests should be separated in two categories.

Another problem which became quickly apparent is that there is an important delay between the detection of a penalty by the Webots referee and the reception of the modified message by the GameController. Especially when using `fast` mode for execution, 8 simulated seconds of margin does not seem to be enough to obtain reliable results (especially when there are multiple messages to be sent to the GameController). I don't know which side is slowing down the process (maybe both), but I think that it is quite important to improve it, not only to make testing easier, but also to make sure that robots are penalized quickly enough.

I also don't see the formatted time before the logs from the referee, I am not sure if/why that was changed, but it's definitely very convenient to have them when debugging as well.

Running the test also exhibits that for illegal entry, it's the robot of the wrong team that is getting penalized and shown a yellow card.

Finally, there are remaining questions to improve the reliability/quality of the automated testing:
- Currently, the `gamestate.py` is reused by simply using a symbolic link and the UDP socket listener is roughly duplicated in the `test_supervisor.py` and `referee.py`. @omichel Is there a *clean* way of expressing dependencies between controllers in Webots?
- I had to take a margin of 3 centimeters between the requested position in the `JSON` files and the position obtained through the supervisor. I guess this is because the robot is not standing upright, but from a testing perspective, I'm not sure how we should compare the values to reduce this error margin. The problem is even more important for checking orientation of the robot (which is not implemented yet).

### CODE REVIEW

**Review by omichel — COMMENTED** [review]
I could review this contribution and it looks overall very good to me.
I just have a couple of minor comments:
1. subfolders of the `tests` folder shouldn't have the `test_` prefix, it looks redundant.
2. target objects are referred to by their name field (e.g., "red player 1"). It would be more convenient and more generic to use their DEF name instead, (e.g., "RED_PLAYER_1" or "BALL").

**Comment by omichel** [comment]
> Another problem which became quickly apparent is that there is an important delay between the detection of a penalty by the Webots referee and the reception of the modified message by the GameController. Especially when using fast mode for execution, 8 simulated seconds of margin does not seem to be enough to obtain reliable results (especially when there are multiple messages to be sent to the GameController). I don't know which side is slowing down the process (maybe both), but I think that it is quite important to improve it, not only to make testing easier, but also to make sure that robots are penalized quickly enough.

I believe this delay comes from the GameController as the referee will immediately notify the GameController whenever an event occurs. You can check it from the log file.

**Comment by omichel** [comment]
> I also don't see the formatted time before the logs from the referee, I am not sure if/why that was changed, but it's definitely very convenient to have them when debugging as well.

The time information appears in the log file, but not in the Webots console. The motivation is that the output in the Webots console is usually checked live and hence the timing information is not useful there (and makes some extra noise), whereas it is important in the `log.txt` file.

**Comment by omichel** [comment]
> Currently, the gamestate.py is reused by simply using a symbolic link and the UDP socket listener is roughly duplicated in the test_supervisor.py and referee.py. @omichel Is there a clean way of expressing dependencies between controllers in Webots?

A possibility would be to add a [runtime.ini file](https://cyberbotics.com/doc/guide/controller-programming#languages-settings) which would include a [Python] section defining the `PYTHONPATH` environment variable pointing to the referee folder (relative path) and thus allowing to import gamestate.py without a symbolic link.

**Comment by omichel** [comment]
> I had to take a margin of 3 centimeters between the requested position in the JSON files and the position obtained through the supervisor. I guess this is because the robot is not standing upright, but from a testing perspective, I'm not sure how we should compare the values to reduce this error margin. The problem is even more important for checking orientation of the robot (which is not implemented yet).

This is because the robot is "dropped" in the world and will need to stabilize at a stable position. To fix this problem you can retrieve the values you get from the supervisor once the robot has stabilized and use these values in the JSON file. The error should then be much lower.

**Comment by medrimonia** [comment]
> I just have a couple of minor comments:

1. Overall naming strategy has been adapted to make it easier to understand the tests, path is now `tests/theme/name` e.g. `tests/positioning/ready`. I think it will be easier to proceed with this once we start having more than 10 tests.
2. That has been solved, I agree it's more convenient.

**Comment by medrimonia** [comment]
> This is because the robot is "dropped" in the world and will need to stabilize at a stable position. To fix this problem you can retrieve the values you get from the supervisor once the robot has stabilized and use these values in the JSON file. The error should then be much lower.

Ok, I see that the stabilization time is higher than what I expected. I think that using a larger margin on position is preferable to using a high margin on time as a default. If some elements require accurate testing of position, one of the option would be to add a field `pos_accuracy` in the `Test` class and use it for comparison.

**Pull request merged**
