### PR TITLE
Improved display

### LINKED ISSUE #170: Improvement/debug of display of game interruptions
This remarks are based on the sequence starting here: https://www.twitch.tv/videos/1047768522?t=0h12m37s

- During the first phase of the free kick, state is still shown as `PLAYING` (while it should indicates which game interruption has been called)
- Once the 'READY' phase of the game interruption starts (internal state=0), the text is set to 'READY' which might easily be confused with the 'READY' main state (while main state is playing)

I would suggest to have two different areas for labels: one for the state and the second one for the secondary state

### LINKED ISSUE #171: Display of warnings, yellow cards and red cards counts
Currently, the different kind of warnings and cards are not shown which makes it harder to understand for the audience to understand what happened if a robot is removed from the field.

### LINKED ISSUE #206: Display simulation time in replay
Currently it's hard to make the link between the logs and the replay of the games because there is no common clock. It would be nice to have a small clock showing the simulation time in the display.

A very nice touch would be to have the option of toggling its display (I don't know if that's possible with the html replay).

### PR DESCRIPTION
**Pull request by omichel**
This PR should fix #206, #171 and #170 by improving the display.
The exiting line is made slightly longer, the font size is very slightly reduced.
A new line is added to be able to display:
- [x] simulation time.
- [x] secondary state.
- [x] secondary time.
- [x] yellow/red cards for each player.
- [x] remaining penalty time for each player.

Here is the result:
robocup

robocup

### CODE REVIEW

**Comment by medrimonia** [comment]
I haven't tested it yet, but what I found weird in the images is that the state indicates:

- 1st image: GoalKick[0] and Normal
- 2nd image:  DirectFreeKick[0] and DirectFreeKick

I would expect one of them to contain the current state and not secondary state.

**Comment by medrimonia** [comment]
And another point that we should worry about as well is that a player can have simultaneously:

- 1 warning and 1 yellow card

I am also unsure about the potential confusion that we could have with a red player having one red card with the proposed approach.

**Comment by omichel** [comment]
> I haven't tested it yet, but what I found weird in the images is that the state indicates:
>
> -    1st image: GoalKick[0] and Normal
> -    2nd image: DirectFreeKick[0] and DirectFreeKick
>
> I would expect one of them to contain the current state and not secondary state.

Yes, the upper part still displays either the main state or the interruption name (if an interruption happens).
The lower part displays the secondary state.
Shall I remove the interruption and display always the main state?

**Comment by omichel** [comment]
> And another point that we should worry about as well is that a player can have simultaneously:
>
> -    1 warning and 1 yellow card

Currently the referee doesn't display warnings at all. I can try to add that.

> I am also unsure about the potential confusion that we could have with a red player having one red card with the proposed approach.

Yes, it's not the same red, so it is actually clearly visible, but I agree it might be confusing. I will think of a better solution including warnings as well...

**Comment by medrimonia** [comment]
> Shall I remove the interruption and display always the main state?

Yes, I think that this having both main state and game interruptions at the same time is preferable, because the secondary state is the interruption. Keeping the color of the team who is awarded the game interruption and the current step of the game interruption is a nice touch.

> Currently the referee doesn't display warnings at all. I can try to add that.

Thank you!

**Comment by omichel** [comment]
I believe I found a better solution for warnings, yellow and green cards (and it is possible to have both a warning and a yellow card, not shown here):
robocup
The game state is displayed at the top right and the secondary state just below.
Colors, game interruption steps and game interruption seconds are displayed appropriately.
The current simulation time should now be in sync with the animation file time, but I kept it in the display for testing (it's easy to remove by deleting [this line](https://github.com/RoboCup-Humanoid-TC/webots/blob/d0134f2a14298dbe88699cbeb44d255bedcc5317/projects/samples/contests/robocup/controllers/referee/referee.py#L2759) and the corresponding function).

**Comment by medrimonia** [comment]
Thank you very much, this looks great!

**Comment by medrimonia** [comment]
The PR has no impact on the automated tests, we're good to go! Thank you a lot!

**Pull request merged**
