### PR TITLE
Game phases second half automated

### PR DESCRIPTION
**Pull request by SoheilKhatibi**
This PR is aimed to test the procedure of starting the second half of a game in an automated way. It relates to issue #6.

### CODE REVIEW

**Comment by medrimonia** [comment]
Isn't it missing the `test_scenario.json` file?

**Comment by SoheilKhatibi** [comment]
I will shortly upload it and the README

**Comment by SoheilKhatibi** [comment]
Just one point is that I have used system time among other simulated clock types. Do you think it is problematic? as you mentioned in the test_supervisor documentation that it is easier to understand if one clock type is used

**Comment by medrimonia** [comment]
This test is one of the cases where it is not possible to stick to one type of clock, so this is ok. It's just that it should be avoided practice when it's possible.

**Pull request merged**
